[WIP] Change event listeners to newer event system + sample fix for natura
ForestryMC/ForestryMC pull request #1794
Opened 2017-08-11 23:31 UTC by Obbi89

This is mainly for discussion on how to approach upcoming problems due to event api changes.

This is a trial and error solution to get a client up and running with changes introduced somewhere between 1.8 and 1.12.
Some mods (including Natura) are using RegistryEvents now. Those events are fired AFTER preInit making any preInit item look ups silently fail.
To fix this the inner workings of Forestry need to redesigned and moved around.
There are some unresolved issues (see comments)

I would use this as a discussion on how to tackle the problem, while providing a glance at some of the required changes.

This whole changeset is not really tested.
Especially everything model related etc. is totally untested. I do not have enough knowledge of the design of Forestry to see if moving some stuff around is actually the right thing to do here and there.

Additionally there will be some more changes to clean some mess up that is already in the code base. (See comments)

2017-08-11 23:44 UTC, Obbi89 commented on src/main/java/forestry/plugins/BlankForestryPlugin.java
> +
TODO: fix whitespace error

2017-08-11 23:44 UTC, Obbi89 commented on src/main/java/forestry/plugins/PluginManager.java
> +	public static void runRegisterCrates(RegistryEvent.Register<Item> event) {
Todo use a functional approach like
```
run(name: string, consumer: Consumer<IForestryPlugin>)
  Log.debug(`{name] begin`)
  foreach plugin in loadedPlugins:
     consumer.apply(plugin)
     Log.debug(`    {plugin} ✓`)
  Log.debug(`{name} complete")
```

2017-08-11 23:44 UTC, Obbi89 commented on src/main/java/forestry/plugins/PluginManager.java
> +	public static void runRegisterCrates(RegistryEvent.Register<Item> event) {
and then just run every stage with a lambda expression.
```run("registerItems", plugin => plugin.registerItems());```

2017-08-11 23:44 UTC, Obbi89 commented on src/main/java/forestry/plugins/PluginManager.java
> -				plugin.registerCrates();
Those needed to be moved to the stage after registering blocks and items.
Maybe one should introduce new stages for this?

The Registry events are executed in alphabetical order by registry names except that items always run after blocks. 
(see forge api documentation)

2017-08-12 21:49 UTC, mezz requested changes
Looks good, needs some small changes or clarifications.

2017-08-12 21:49 UTC, mezz commented on src/main/java/forestry/Forestry.java
> +		dependencies = "required-after:forge@[14.21.1.2424,);"
Please pick the minimum version of Forge that will work, 2424 doesn't seem to have an important change. 
Also add a comment on this line saying which new feature of Forge is required.

2017-08-12 21:49 UTC, mezz commented on src/main/java/forestry/plugins/compat/PluginNatura.java
> +//import forestry.farming.logic.FarmableSapling;
remove commented-out import

2017-08-12 21:49 UTC, mezz commented on src/main/java/forestry/plugins/compat/PluginNatura.java
> +					// XXX: getMaxAge
what does the `XXX` comment mean?

2017-08-12 22:15 UTC, Obbi89 commented on src/main/java/forestry/Forestry.java
> +		dependencies = "required-after:forge@[14.21.1.2424,);"
I guess that one slipped in there... I need to check when or why I pushed the version. If not required I'll revert that change

2017-08-12 22:17 UTC, Obbi89 commented on src/main/java/forestry/plugins/compat/PluginNatura.java
> +					// XXX: getMaxAge
XXX is the same as HACK.
Reflection is a hack in my eyes but regarding Minecraft modding in general I guess I can remove that note.

Maybe there is a better way to query custom attributes from items. But as far as I can see that's the easiest one.

2017-08-12 22:30 UTC, Obbi89 commented
Ok changes should be applied

2017-08-12 22:50 UTC, mezz approved these changes

2017-08-12 22:50 UTC, merged