Natura huge glowshrooms can be autofarmed using shroom logic
ForestryMC/ForestryMC pull request #1859
Opened 2017-09-25 00:28 UTC by LachimHeigrim

Natura's huge glowshrooms can be auto-farmed using mushroom logic. Note for testing: they seem to grow extremely slowly, but almost instantly grow huge ones after bonemealing if enough space is around them (edge of farm).

I struggled to find a way how to tie together shroom's subitem, shroom's blockstate and corresponding large shroom block without touching Natura's API directly. Would appreciate review and example refactor for learning. :)

Also I noticed when `getFarmableForBlock()` in `FarmArboreal` is called for air block it still iterates through farmables which is unnecessary, so I added fast return.

Finally I added shrooms for crating, they were ignored previously.

2017-09-25 00:30 UTC, LachimHeigrim commented on src/main/java/forestry/plugins/compat/PluginNatura.java
> +					final Block largeShroomBlock =
How can I find corresponding huge mushroom block for subitem (without touching Natura API)?

2017-10-14 09:20 UTC, LachimHeigrim commented
Hi folks,

just a friendly reminder. Is there any problem integrating my pull requests? 

Thanks,
Lach

2017-10-14 13:13 UTC, Nedelosk commented on src/main/java/forestry/farming/logic/FarmLogicArboreal.java
> +		if (blockState.getBlock() != Blocks.AIR) {
Can you please change this to !world.isAirBlock(position) ?

2017-10-15 01:29 UTC, mezz requested changes

2017-10-15 01:29 UTC, mezz commented on src/main/java/forestry/plugins/compat/PluginNatura.java
> +										? greenLargeGlowshroomBlock : purpleLargeGlowshroomBlock;
Please split up this ternary statement into if/else form

2018-02-17 14:54 UTC, closed without merging