More Dimension Blacklists
ForestryMC/ForestryMC pull request #1942
Opened 2018-01-08 17:59 UTC by temp1011

This should hopefully sort out trees and ores. The code is pretty much the same as the other PR.

2018-01-08 22:15 UTC, Nedelosk requested changes

2018-01-08 22:15 UTC, Nedelosk commented on src/main/java/forestry/arboriculture/worldgen/TreeDecorator.java
> +		if(Config.blacklistedTreeDims.contains(world.provider.getDimension()))
Please move this check up to  decorateTrees(World, Random, int, int). It makes not much sense to check it every time if the world is every time the same.

2018-01-08 23:10 UTC, Nedelosk approved these changes

2018-01-09 05:52 UTC, mezz approved these changes

2018-01-14 20:16 UTC, merged