Add whitelist for generation based on dimension
ForestryMC/ForestryMC pull request #1968
Opened 2018-02-03 18:22 UTC by temp1011

Closes https://github.com/ForestryMC/ForestryMC/issues/1739. I don't think it's possible to change where the Apiarist village house will generate easily so I haven't touched that. However, I think it is possible to implement a whitelist as well for dimensions. This is designed for pack makers/players (eg - player has access to many dimensions early but pack maker wants to gate forestry until later) as the blacklist will take priority (as it should do in my opinion).

However, this is slightly messy. If there's a better way to do something like this let me know.

2018-02-03 18:29 UTC, Nedelosk commented on src/main/java/forestry/apiculture/HiveConfig.java
> +		return true;
This should be `false`.

2018-02-03 18:30 UTC, Nedelosk requested changes

2018-02-03 18:30 UTC, Nedelosk commented on src/main/java/forestry/apiculture/HiveConfig.java
> +		return true;
This should be `false`.

2018-02-03 18:34 UTC, temp1011 commented on src/main/java/forestry/apiculture/HiveConfig.java
> +		return true;
done

2018-02-03 18:50 UTC, Nedelosk approved these changes

2018-02-04 04:03 UTC, mezz approved these changes

2018-02-16 16:09 UTC, merged