Add IMC for registering flowers
ForestryMC/ForestryMC pull request #2027
Opened 2018-03-08 15:20 UTC by temp1011

This PR lets mods register their own flowers with forestry. This works a lot better than doing it through plugins on the forestry side since another mod has much better access to it's own blockstates.

For example, in https://github.com/ForestryMC/ForestryMC/issues/2022 rather than forestry checking when an agricraft config option is disabled then finding the correct blockstate and registering it there could be a plugin for Forestry in agricraft to just send an imc if the config option is changed (I would be happy to write this plugin).

2018-04-12 19:56 UTC, mezz requested changes
Looks good, I like the idea.

2018-04-12 19:56 UTC, mezz commented on src/main/java/forestry/apiculture/ModuleApiculture.java
> +			try {
This method is getting very long, can you separate out these new cases into new methods?

2018-04-13 01:19 UTC, temp1011 commented
Should the `try/catch` be inside or outside the method call? Inside looks a bit weird but outside increases the other method length.

2018-04-13 02:02 UTC, mezz commented
Inside is fine I think.

2018-04-13 02:02 UTC, mezz approved these changes

2018-04-27 11:51 UTC, merged