Add configuration for crates
ForestryMC/ForestryMC pull request #2047
Opened 2018-03-18 21:59 UTC by temp1011

Closes https://github.com/ForestryMC/ForestryMC/issues/2008. Needs localization but that should essentially be the same as the backpack config apart from the fact we don't display the default items in crates here.

2018-03-18 23:25 UTC, temp1011 commented
I'm assuming I should add this to forge? Recipes are blacklisted but other than that would be nice to have.

2018-03-18 23:28 UTC, temp1011 commented
https://github.com/MinecraftForge/MinecraftForge/pull/4807

2018-04-01 19:36 UTC, temp1011 commented
PR to Forge was merged so we don't need to register fences and fence gates anymore.

2018-04-13 01:29 UTC, temp1011 commented
Fixed conflicts

2018-04-29 18:44 UTC, mezz commented
To make reviewing easier, please try to keep commits to one small subject.
This one can be broken into:

1. Add configuration for crates
2. Formatting fixes (on unrelated files)
3. Remove oredict registration for fences and fence gates

If there is a problem with any one of these, the PR gets stalled and it makes changes harder to review. If they are separate, I can merge 2 good ones and comment on the one that needs fixing.

Review:

We shouldn't remove the oredict registration without increasing the minimum forge version.
Now that localization is merged into the main project here, these configs need localization in the same PR.

2018-04-29 21:23 UTC, temp1011 commented
I've bumped to the latest recommended forge version which includes the commit to add fences to the forge oredict. It would be good if someone with direct commit privileges could format the whole code base. I could open a PR but it would get outdated quite quickly.

2018-04-29 21:40 UTC, mezz requested changes

2018-04-29 21:40 UTC, mezz commented on gradle.properties
> +forgeversion=14.23.3.2655
This is the forge version used in development. 
It's good to update this, but we also need to update the minimum required version here: https://github.com/ForestryMC/ForestryMC/blob/f52cc3893b2797c7e25761fc24f7ed2e6859c561/src/main/java/forestry/Forestry.java#L71

Look through the [forge changelog here](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.3.2676/forge-1.12.2-14.23.3.2676-changelog.txt) to find which version adds the oredict entries, and use that version as the minimum required.

2018-04-29 22:03 UTC, temp1011 commented
```
Build 1.12.2-14.23.2.2643:
	34900092+temp1011: Add fences and fence gates to ore dictionary (#4807)```
I believe this should be the right version

2018-04-29 22:40 UTC, mezz approved these changes
Looks good to me.
@Nedelosk if you can test this, I think it will be ready to merge.

2018-05-01 17:06 UTC, Nedelosk commented
It would be good if you could add more information to the comments of the config options. Things like how an entry has to look like. `Added / Blacklisted items` is not much information for a user that sees the config for the first time.

2018-05-01 17:07 UTC, Nedelosk requested changes
.

2018-05-01 17:19 UTC, Nedelosk commented
@temp1011 Have you tested it yourself ? You should always test thing if you make a PR. You are parsing the config at `doInit` but all creates get created in the `RegistryEvent.Register<Item>` event and that is called directly after `preInit`. So currently you can only add items with the config.

2018-05-01 17:29 UTC, Nedelosk requested changes
Have you tested it yourself ? You should always test thing if you make a PR. Currently you can only add items with the config.

2018-05-01 17:29 UTC, Nedelosk commented on src/main/java/forestry/storage/ModuleCrates.java
> +	public static List<ItemStack> cratesRejectedItem = new ArrayList<>();
Can you please change this to a map with an `Item` key and and a `List` value or you use a `Multimap`. This way you not have to iterate over every stack even it the stack has nothing todo with the item.

2018-05-01 17:29 UTC, Nedelosk commented on src/main/java/forestry/storage/CrateRegistry.java
> +		if (ModuleCrates.cratesRejectedOreDict.contains(oreDictName)) {
Can you please add a 'blacklistCrate' function to the 'ICrateRegistry' interface.

2018-05-01 17:29 UTC, Nedelosk commented on src/main/resources/assets/forestry/lang/en_us.lang
> +for.config.crates.items.accepted.comment=Added items
t would be good if you could add more information to the comments of the config options. Things like how an entry has to look like or a list of all entries that can be blacklisted. Added / Blacklisted items is not much information for a user that sees the config for the first time.

2018-05-01 17:29 UTC, Nedelosk commented on src/main/java/forestry/storage/ModuleCrates.java
> +	public void doInit() {
You are parsing the config at `doInit` but all creates get created in the `RegistryEvent.Register<Item>` event and that is called directly after `preInit`.

2018-05-01 18:25 UTC, temp1011 commented
I thought I had it working... I haven't addressed everything yet because I don't have enough time. However, I do wonder whether having this as a Json might be nice. But I will fix this first and then think about that when working on the Json recipes.

2018-05-04 15:52 UTC, temp1011 commented
If this needs better support let me know.

2018-05-11 09:03 UTC, Nedelosk approved these changes

2018-05-11 09:04 UTC, merged