Clean up code
ForestryMC/ForestryMC pull request #2053
Opened 2018-03-24 01:18 UTC by temp1011

This is the stuff that analysis bought up that I couldn't find any reason to justify keeping. It's mostly just minor stuff like imports. There's probably a lot more that could be done but I'm trying not to break anything in the process and not have a diff going into hundreds of lines.

2018-03-24 01:20 UTC, temp1011 commented
https://github.com/ForestryMC/ForestryMC/blob/54a9da917dc09cc6e7800001cd1eee7320021da1/src/main/java/forestry/greenhouse/multiblock/blocks/world/NextTickEntry.java#L38

This was so weird I feel like there is actually a reason for this (probably some concurrency stuff over my head).

2018-03-29 00:47 UTC, temp1011 commented on src/main/java/forestry/core/utils/Translator.java
> +			return net.minecraft.util.text.translation.I18n.translateToFallback(key);    //no equivalent from what I can see
This doesn't seem to have a replacement. If we don't use it the unformatted String will be displayed. Not sure what the best option is.

2018-04-12 19:55 UTC, mezz commented
I don't think it's very safe to make these `I18n` changes, can you separate them into a different commit?

2018-04-12 20:05 UTC, Nedelosk requested changes

2018-04-12 20:05 UTC, Nedelosk commented on src/main/java/forestry/arboriculture/genetics/TreeDefinition.java
> +		leafProvider.init(this.species);
You don't have to call `init` manually it gets called in the `build` method of the species. https://github.com/ForestryMC/ForestryMC/blob/36ccd5c3e1f1aa3f600bbcdd6111b2bd090c64ca/src/main/java/forestry/arboriculture/genetics/alleles/AlleleTreeSpecies.java#L87-L92

2018-04-13 01:48 UTC, temp1011 commented
`IL8N` removed, conflicts fixed.

2018-04-13 02:38 UTC, mezz requested changes

2018-04-13 02:38 UTC, mezz commented on src/main/java/forestry/arboriculture/models/SimpleModel.java
> +					throw new RuntimeException(e);
this should be
```java
Throwables.throwIfUnchecked(e);
throw new RuntimeException(e);
```
That way the exception is only wrapped if it needs to be.

You can find out more about it here: https://github.com/google/guava/wiki/Why-we-deprecated-Throwables.propagate

2018-04-15 16:29 UTC, temp1011 commented
Pretty sure the reflection for `CriteriaTriggers.register()` isn't needed any more.

2018-04-16 01:18 UTC, mezz approved these changes

2018-05-01 17:46 UTC, Nedelosk approved these changes

2018-05-01 17:48 UTC, merged