Improve Industrialcraft2 plugin
ForestryMC/ForestryMC pull request #2057
Opened 2018-03-24 16:10 UTC by temp1011

Requires https://github.com/ForestryMC/ForestryMC/pull/2050.

Some small fixes to `PluginIC2` to let rubber trees work in the normal tree farm again and clean up backpacks and crates a bit.

2018-04-06 14:16 UTC, Nedelosk requested changes
Could you please use the new Module Helper that I added with the last commit.

2018-04-09 15:43 UTC, temp1011 commented
Now uses `ModuleHelper`

2018-04-15 16:07 UTC, temp1011 commented
Would be nice if I could improve this https://github.com/ForestryMC/ForestryMC/blob/24c8add7fcba5b3067eff8244ef4b0442658460d/src/main/java/forestry/farming/logic/crops/CropRubber.java#L43-L59 Are the IC2 people good at adding to the API is people ask them too?

2018-05-27 12:03 UTC, temp1011 commented
This now fixes #2139.

2018-05-27 23:05 UTC, mezz requested changes
Looks good, just one minor thing.

2018-05-27 23:05 UTC, mezz commented on src/main/java/forestry/plugins/PluginIC2.java
>  			Log.error("IC2 Recipes.recyclerBlacklist not found.");
This will log if apiculture is disabled, there should be no log in that case.

2018-05-27 23:19 UTC, mezz approved these changes

2018-05-28 12:05 UTC, merged