Tech reborn plugin
ForestryMC/ForestryMC pull request #2078
Opened 2018-04-09 15:31 UTC by temp1011

https://github.com/ForestryMC/ForestryMC/pull/2058 messed up. Now uses module helper.

2018-04-09 16:17 UTC, temp1011 commented
If metadata is completely gone and there isn't a good way to get blockstates through forge it may be worth to start using `@Opitional.Interface` in forge. That way we don't have to include the interface but still get access to it. The disadvantage is forestry then has to load after that mod.

2018-04-09 16:51 UTC, Nedelosk commented
@temp1011 What are you talking about ?

2018-04-09 18:57 UTC, temp1011 commented
https://github.com/MinecraftForge/MinecraftForge/blob/d0bdb233000ac9aff049c5ae2ad8043480a96af9/src/main/java/net/minecraftforge/fml/common/Optional.java

2018-04-12 00:13 UTC, temp1011 commented
@Nedelosk I've changed some things to use the tech reborn interface in the plugin. This should run fine without Tech Reborn installed. However, for the dev environment I think the API will be needed so things compile. Luckily we can get this off of the curse maven API.

2018-04-12 20:35 UTC, mezz requested changes

2018-04-12 20:35 UTC, mezz commented on src/main/java/forestry/farming/logic/crops/CropRubber.java
> +				if (wetPropertyEntry.getKey() instanceof PropertyBool && wetPropertyEntry.getKey().getName().equals("hassap")) {
Below this we have `IProperty<?> property = wetPropertyEntry.getKey();`, you should use `property` here instead of calling `getKey()` more times.

2018-04-12 20:35 UTC, mezz commented on src/main/java/forestry/farming/logic/crops/CropRubber.java
> +			baseState, IProperty<T> property, String valueString) {
I'd prefer to keep this on one line

2018-04-12 20:35 UTC, mezz commented on src/main/java/forestry/farming/logic/crops/CropRubber.java
> +		if (PluginIC2.rubberWood != null && ItemStackUtil.equals(world.getBlockState(pos).getBlock(), PluginIC2.rubberWood)) {
Store `world.getBlockState(pos).getBlock()` in a variable so it is never called twice.

2018-04-12 20:35 UTC, mezz commented on src/main/java/forestry/plugins/PluginTechReborn.java
> +		ItemRegistryApiculture beeItems = ModuleApiculture.getItems();
Check that `ModuleApiculture` is loaded, this line will crash when the apiculture module is disabled in the config.

2018-04-13 00:42 UTC, temp1011 commented
I've added the maven to `build.gradle` because I believe it's necessary for compilation in a dev environment. Is the `@Optional.Interface` stuff OK?

2018-04-13 01:56 UTC, mezz requested changes
Looking good, `@Optional` is fine for this.

2018-04-13 01:56 UTC, mezz commented on build.gradle
> +	compile "TechReborn:TechReborn-${TR_mcversion}:${TR_version}:api"
Should this be `deobfCompile` like the others?

2018-04-13 01:56 UTC, mezz commented on src/main/java/forestry/plugins/PluginTechReborn.java
> +	@Optional.Method(modid = "techreborn")
Please use `MOD_ID` instead of `"techreborn"` for these

2018-04-13 02:47 UTC, mezz approved these changes

2018-04-27 11:50 UTC, merged

2018-05-07 23:55 UTC, temp1011 commented
The Techreborn API does give me some errors when running minecraft in dev about incompatible classloaders which 'will not work'. Not sure why I get those but I have similar errors for JEI and greenhouse so it doesn't seem to cause any issues.