fix bottler dupe
ForestryMC/ForestryMC pull request #2128
Opened 2018-05-07 23:43 UTC by temp1011

Closes https://github.com/ForestryMC/ForestryMC/issues/2126. The new behaviour will keep the stack in the emptying slot until it is completely empty but also decrease the fluid amount in it. Maybe that's not the correct way for it to work. I also ran into a weird bug where it seemed the bottler operation took longer for bigger tanks. Maybe that's intentional.

If there's a better way to fix this just ignore this one :smile: .

2018-05-10 07:23 UTC, Nedelosk requested changes

2018-05-10 07:23 UTC, Nedelosk commented on src/main/java/forestry/core/fluids/FluidHelper.java
> +							inv.setInventorySlotContents(inputSlot, newStack.copy());
You don't have to copy the stack. It already is the copied version of `drainedItem`.

2018-05-10 07:25 UTC, Nedelosk commented on src/main/java/forestry/core/fluids/FluidHelper.java
> +							inv.setInventorySlotContents(inputSlot, newStack.copy());
And why do you check `isFillableContainerWithRoom` ? What if the stack only can be drained  ?

2018-05-10 10:30 UTC, temp1011 commented
Ah yeah this is wrong at the moment. I'll fix it when I have time (hopefully this weekend).

2018-05-11 12:21 UTC, temp1011 commented
I just need to test this but hopefully the code is better now.
EDIT: testing is proving difficult to do...

2018-05-11 13:31 UTC, temp1011 commented
After much stupidity on my part I'm reasonably sure this works now. I have tested it with a thermal expansion tank and it works just fine.

2018-05-11 16:30 UTC, Nedelosk approved these changes

2018-05-18 13:36 UTC, temp1011 commented
Maybe I should refactor `FluidHelper` to have base methods to check `isDrainable` and `isFillable` and tchecking for fill levels?

2018-07-16 21:42 UTC, temp1011 commented
Any update on this?

2018-07-17 04:51 UTC, mezz approved these changes

2018-07-17 10:50 UTC, merged