add methods to allow formatting config comments
ForestryMC/ForestryMC pull request #2197
Opened 2018-07-17 14:49 UTC by temp1011

This came up while working on something else. Adds methods to `LocalizedConfiguration` to allow formatted comment keys. Also removes canTranslate check. I think it's better if something formatted is displayed rather than just the key. However, I can revert this.

Common config after this: https://gist.github.com/temp1011/6dc8d96304a7647f40eaa27f3dd85304.

2018-08-02 04:53 UTC, mezz commented
I see some errors with reporting the defaults when looking at a diff of the old and new configs. Please take a close look that everything matches except for the config comments.

2018-08-02 04:54 UTC, mezz requested changes
I see some differences in the diff, like missing "default" or incorrect arrays in the defaults. Please make sure the only changes are to the config comments.

2018-08-02 13:14 UTC, temp1011 commented
[new config](https://gist.github.com/temp1011/2ff1bfad740000ac8d41fb4d9acdfd24). I think this now has no differences with the old config apart from the addition of some comments.

2018-08-03 04:15 UTC, mezz requested changes
looks good except for a small typo

2018-08-03 04:15 UTC, mezz commented on src/main/java/forestry/core/config/LocalizedConfiguration.java
> +	private String getValiedOptions(Property prop) {
method name has a typo

2018-08-03 10:06 UTC, temp1011 commented on src/main/java/forestry/core/config/LocalizedConfiguration.java
> +	private String getValiedOptions(Property prop) {
oops, sorry

2018-08-04 21:26 UTC, mezz approved these changes

2018-08-12 10:22 UTC, merged